In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [2]:
df = pd.read_csv('./data/sleep_stage_info.csv')

In [3]:
list_df = pd.read_csv('./data/peak_algorithm_mini.csv')

In [7]:
p_995 = list_df[list_df['patient_id'] == 995].reset_index(drop=True)
p_999 = list_df[list_df['patient_id'] == 999].reset_index(drop=True)

In [8]:
p_999

     sliced_audio_file_id  peak_algorithm  patient_id
0     00000999_01_000_000               3         999
1     00000999_01_000_001               1         999
2     00000999_01_000_002               5         999
3     00000999_01_001_000               5         999
4     00000999_01_001_001               3         999
...                   ...             ...         ...
1477  00000999_05_127_025               6         999
1478  00000999_05_127_026              10         999
1479  00000999_05_127_027               7         999
1480  00000999_05_127_028               2         999
1481  00000999_05_127_029               2         999

[1482 rows x 3 columns]

In [14]:
random_995 = np.random.choice(p_995.shape[0], 5, replace=False)
random_999 = np.random.choice(p_999.shape[0], 5, replace=False)

maxidx_995 = p_995['peak_algorithm'].idxmax()
maxidx_999 = p_999['peak_algorithm'].idxmax()

minidx_995 = p_995['peak_algorithm'].idxmin()
minidx_999 = p_999['peak_algorithm'].idxmin()

p_995.iloc[random_995]
p_999.iloc[random_999]

p_995.iloc[[maxidx_995, minidx_995]]
p_999.iloc[[maxidx_999, minidx_999]]

sample_df = pd.concat([p_995.iloc[random_995], p_999.iloc[random_999], p_995.iloc[[maxidx_995, minidx_995]], p_999.iloc[[maxidx_999, minidx_999]]]).reset_index(drop=True)

In [17]:
sample_df.sort_values(by=['patient_id', 'sliced_audio_file_id']).reset_index(drop=True)

   sliced_audio_file_id  peak_algorithm  patient_id
0   00000995_01_000_000               0         995
1   00000995_01_002_051              12         995
2   00000995_01_008_056               8         995
3   00000995_01_012_112               6         995
4   00000995_02_017_002               5         995
5   00000995_04_039_007               7         995
6   00000995_04_042_021               6         995
7   00000999_01_004_033               0         999
8   00000999_02_038_002               4         999
9   00000999_03_087_000               3         999
10  00000999_03_089_004               0         999
11  00000999_03_095_032              11         999
12  00000999_03_095_036               9         999
13  00000999_04_123_007               4         999

In [18]:
sample_df.to_csv('./data/peak_test.csv', index=False)